
CREATE TABLE IF NOT EXISTS register(
	id INT(10) AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	profile VARCHAR(255) DEFAULT 'default.jpg', 
	date_time DATETIME
);




CREATE TABLE IF NOT EXISTS userdata(
	id INT(10) AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL,
	
	user_content VARCHAR(255) NOT NULL,
	content_image VARCHAR(255) NOT NULL,
	date_time DATETIME
);


CREATE TABLE IF NOT EXISTS likes(
id INT(10) AUTO_INCREMENT PRIMARY KEY,
user_id VARCHAR(255) NOT NULL,
object_id VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS haha(
id INT(10) AUTO_INCREMENT PRIMARY KEY,
user_id VARCHAR(255) NOT NULL,
object_id VARCHAR(255) NOT NULL
);